export const IMAGE_COMPONENTS = {
    logo: require("../assets/images/logo.png"),
    profileImg: require("../assets/images/profile.jpg"),
    copperAlleyBar: require("../assets/images/copperAlleyBar.png"),
    copperAlleyBar1: require("../assets/images/copperAlleyBar1.png"),
    shopDetails: require("../assets/images/shopDetails.png"),
    mojito: require("../assets/images/Mojito.png"),
    purpleHaze: require("../assets/images/PurpleHaze.png"),
    item1: require("../assets/images/item1.png"),
    item2: require("../assets/images/item2.png"),
    item3: require("../assets/images/item3.png"),
    item4: require("../assets/images/item4.png"),
    item5: require("../assets/images/item5.png"),
    item6: require("../assets/images/item7.png"),
    successImg: require("../assets/images/succeccImg.png"),
    emptyImg: require("../assets/images/emptyImg.png"),
    profile1: require("../assets/images/pp1.png"),
    profile2: require("../assets/images/pp2.png"),
    profile3: require("../assets/images/pp3.png"),
} as const;